[build]
  command = "pnpm run build"
  publish = ".next"
  environment = { NODE_VERSION = "18", PNPM_VERSION = "8" }

[plugins]
  - package = "@netlify/plugin-nextjs"

[functions]
  directory = "functions"

[template.environment]
  NEXT_PUBLIC_BASE_URL = "Base URL for your application"
  NEXT_PUBLIC_API_URL = "API URL for your application"
  DB_USER = "Database user"
  DB_HOST = "Database host"
  DB_NAME = "Database name"
  DB_PASSWORD = "Database password"
  DB_PORT = "Database port (default 5432)"
  DB_SSL = "Use SSL for database connection (true/false)"